version: '3'

services:
  hc-api-mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - hc-api-mongo:/var/lib/hc-api-mongo/data

volumes:
  hc-api-mongo:
