export enum CareerTypesEnum {
  COVID_PATIENT_CARE_ASSISTANT = 'COVID Patient Care Assistant',
  MEDICAL_ASSISTANT = 'Medical Assistant',
  EKG_TECHNICIAN = 'EKG Technician',
  PATIENT_CARE_TECHNICIAN = 'Patient Care Technician',
  NURSE_ASSISTANT = 'Nurse Assistant',
  DIALYSIS_TECHNICIAN = 'Dialysis Technician',
  MEDICAL_BILLING = 'Medical Billing',
  MEDICAL_OFFICE_ADMINISTRATION = 'Medical Office Administration',
  PHLEBOTOMY_TECHNICIAN = 'Phlebotomy Technician',
  CERTIFIED_NURSE_AIDE = 'Certified Nurse Aide',
  PERSONAL_CARE_AIDE = 'Personal Care Aide',
  HOME_HEALTH_AIDE = 'Home Health Aide',
  BLS_CPR = 'BLS/CPR',
  MEDICAL_CODING = 'Medical Coding',
  PHARMACY_TECHNICIAN = 'Pharmacy Technician',
}
